import { APP_PREFIX_PATH } from 'constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'
import { ADMIN, USER } from 'constants/roles.constant'

const appsNavigationConfig = [
    {
        key: 'apps',
        path: '',
        title: 'APPS',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            // {
            //     key: 'apps.project',
            //     path: '',
            //     title: 'Project',
            //     translateKey: 'nav.appsProject.project',
            //     icon: 'project',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsProject.dashboard',
            //             path: `${APP_PREFIX_PATH}/project/dashboard`,
            //             title: 'Dashboard',
            //             translateKey: 'nav.appsProject.dashboard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsProject.projectList',
            //             path: `${APP_PREFIX_PATH}/project/project-list`,
            //             title: 'Project List',
            //             translateKey: 'nav.appsProject.projectList',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsProject.scrumBoard',
            //             path: `${APP_PREFIX_PATH}/project/scrum-board`,
            //             title: 'Scrum Board',
            //             translateKey: 'nav.appsProject.scrumBoard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsProject.issue',
            //             path: `${APP_PREFIX_PATH}/project/issue`,
            //             title: 'Issue',
            //             translateKey: 'nav.appsProject.issue',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.crm',
            //     path: '',
            //     title: 'CRM',
            //     translateKey: 'nav.appsCrm.crm',
            //     icon: 'crm',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            // {
            //     key: 'appsCrm.dashboard',
            //     path: `${APP_PREFIX_PATH}/crm/dashboard`,
            //     title: 'Dashboard',
            //     translateKey: 'nav.appsCrm.dashboard',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [ADMIN, USER],
            //     subMenu: [],
            // },
            // {
            //     key: 'appsCrm.calendar',
            //     path: `${APP_PREFIX_PATH}/crm/calendar`,
            //     title: 'Calendar',
            //     translateKey: 'nav.appsCrm.calendar',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [ADMIN, USER],
            //     subMenu: [],
            // },
            {
                key: 'appsCrm.customers',
                path: `${APP_PREFIX_PATH}/crm/customers`,
                title: 'მომხმარებლები',
                translateKey: 'nav.appsCrm.customer',
                icon: 'crm', type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
            {
                key: 'appsCrm.staff',
                path: `${APP_PREFIX_PATH}/crm/staff`,
                title: 'თანამშრომლები',
                translateKey: 'nav.appsCrm.staff',
                icon: 'crm', type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'appsCrm.trainer',
                path: `${APP_PREFIX_PATH}/crm/trainer`,
                title: 'ტრენერები',
                translateKey: 'nav.appsCrm.trainer',
                icon: 'crm', type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'appsCrm.workout',
                path: `${APP_PREFIX_PATH}/crm/workout`,
                title: 'სავარჯიშო ჯგუფები',
                translateKey: 'nav.appsCrm.workout',
                icon: 'crm', type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'appsCrm.aboniments',
                path: `${APP_PREFIX_PATH}/crm/aboniments`,
                title: 'აბონიმენტები',
                translateKey: 'nav.appsCrm.aboniments',
                icon: 'forms', type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            // {
            //     key: 'appsCrm.customerDetails',
            //     path: `${APP_PREFIX_PATH}/crm/customer-details?id=8`,
            //     title: 'Customer Details',
            //     translateKey: 'nav.appsCrm.customerDetails',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [ADMIN, USER],
            //     subMenu: [],
            // },
            //     ],
            // },
            {
                key: 'apps.account',
                path: '',
                title: 'Account',
                translateKey: 'nav.appsAccount.account',
                icon: 'account',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAccount.settings',
                        path: `${APP_PREFIX_PATH}/account/settings/profile`,
                        title: 'Settings',
                        translateKey: 'nav.appsAccount.settings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.activityLog',
                        path: `${APP_PREFIX_PATH}/account/activity-log`,
                        title: 'Activity Log',
                        translateKey: 'nav.appsAccount.activityLog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default appsNavigationConfig
